// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: transcode.proto
#ifndef GRPC_transcode_2eproto__INCLUDED
#define GRPC_transcode_2eproto__INCLUDED

#include "transcode.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace transcoder {

class Transcoder GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::transcoder::TranscodeResponse>> Transcode(::grpc::ClientContext* context, const ::transcoder::TranscodeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::transcoder::TranscodeResponse>>(TranscodeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::transcoder::TranscodeResponse>> AsyncTranscode(::grpc::ClientContext* context, const ::transcoder::TranscodeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::transcoder::TranscodeResponse>>(AsyncTranscodeRaw(context, request, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::transcoder::TranscodeResponse>* TranscodeRaw(::grpc::ClientContext* context, const ::transcoder::TranscodeRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::transcoder::TranscodeResponse>* AsyncTranscodeRaw(::grpc::ClientContext* context, const ::transcoder::TranscodeRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::transcoder::TranscodeResponse>> Transcode(::grpc::ClientContext* context, const ::transcoder::TranscodeRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::transcoder::TranscodeResponse>>(TranscodeRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::transcoder::TranscodeResponse>> AsyncTranscode(::grpc::ClientContext* context, const ::transcoder::TranscodeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::transcoder::TranscodeResponse>>(AsyncTranscodeRaw(context, request, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReader< ::transcoder::TranscodeResponse>* TranscodeRaw(::grpc::ClientContext* context, const ::transcoder::TranscodeRequest& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::transcoder::TranscodeResponse>* AsyncTranscodeRaw(::grpc::ClientContext* context, const ::transcoder::TranscodeRequest& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_Transcode_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Transcode(::grpc::ServerContext* context, const ::transcoder::TranscodeRequest* request, ::grpc::ServerWriter< ::transcoder::TranscodeResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Transcode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Transcode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Transcode() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transcode(::grpc::ServerContext* context, const ::transcoder::TranscodeRequest* request, ::grpc::ServerWriter< ::transcoder::TranscodeResponse>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTranscode(::grpc::ServerContext* context, ::transcoder::TranscodeRequest* request, ::grpc::ServerAsyncWriter< ::transcoder::TranscodeResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Transcode<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Transcode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Transcode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Transcode() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Transcode(::grpc::ServerContext* context, const ::transcoder::TranscodeRequest* request, ::grpc::ServerWriter< ::transcoder::TranscodeResponse>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace transcoder


#endif  // GRPC_transcode_2eproto__INCLUDED
